version: "3.3"
services: 
  lbc:
    build:
      args: 
        WORK_DIR: /go/src/github.com/MydroX/lbc
    container_name: lbc
    ports:
      - 3000:3000
    volumes: 
      - ../.:/go/src/github.com/MydroX/lbc
    networks: 
      - lbc

networks:
  lbc:
    external: true
  